"""Testes do PostFlowService cobrindo o fluxo principal (com fakes do PostGenerator/Replicate/GCS).

Cada teste roda o flow completo via handle_command + wait_pending — o spawn
está em background. Counts esperados no happy path:
  sent_messages: [0] insights, [1] post bilíngue com botões
  sent_photos:   [0] foto com caption truncado em PT
"""

from typing import NamedTuple

import pytest

from bot_posts_linkedin.config import get_settings
from bot_posts_linkedin.domain.rejection_cause import RejectionCause
from bot_posts_linkedin.domain.states import PostStatus
from bot_posts_linkedin.services.post_flow import PostFlowService
from bot_posts_linkedin.store.chat_state_memory import InMemoryChatStateStore
from bot_posts_linkedin.store.memory import InMemoryPostStore
from tests.fakes import (
    FakeAnthropicClient,
    FakeGcsImageStorage,
    FakeGithubSearchService,
    FakeLinkedInPublisher,
    FakePostGenerator,
    FakeReplicateImageService,
    FakeTelegramClient,
)

CHAT_ID = "999"


class _Bundle(NamedTuple):
    service: PostFlowService
    telegram: FakeTelegramClient
    posts: InMemoryPostStore
    chats: InMemoryChatStateStore
    anthropic: FakeAnthropicClient
    github: FakeGithubSearchService
    post_gen: FakePostGenerator
    replicate: FakeReplicateImageService
    gcs: FakeGcsImageStorage
    linkedin: FakeLinkedInPublisher


def _make_service() -> _Bundle:
    telegram = FakeTelegramClient()
    posts = InMemoryPostStore()
    chats = InMemoryChatStateStore()
    anthropic = FakeAnthropicClient()
    github = FakeGithubSearchService()
    post_gen = FakePostGenerator()
    replicate = FakeReplicateImageService()
    gcs = FakeGcsImageStorage()
    linkedin = FakeLinkedInPublisher(dry_run=False)
    service = PostFlowService(
        post_store=posts,
        chat_state_store=chats,
        telegram_client=telegram,
        anthropic_client=anthropic,
        github_search=github,
        post_generator=post_gen,
        replicate_image=replicate,
        gcs_image=gcs,
        linkedin_publisher=linkedin,
        settings=get_settings(),
    )
    return _Bundle(
        service, telegram, posts, chats, anthropic, github, post_gen, replicate, gcs, linkedin
    )


async def _get_awaiting_post(posts: InMemoryPostStore):
    awaiting = await posts.list_by_status(PostStatus.AWAITING_APPROVAL)
    assert len(awaiting) == 1, f"esperado 1 post em AWAITING_APPROVAL, achei {len(awaiting)}"
    return awaiting[0]


@pytest.mark.asyncio
async def test_happy_path_command_para_aprovacao() -> None:
    b = _make_service()
    b.post_gen.set_body_response(
        "Post em português gerado pelo fake.",
        "Post in English generated by the fake.",
    )

    await b.service.handle_command(CHAT_ID, "teste de assunto", use_github=False)
    await b.service.wait_pending()

    # Insights + post bilíngue
    assert len(b.telegram.sent_messages) == 2
    insights, post_msg = b.telegram.sent_messages
    assert "Insumos coletados" in insights["text"]
    assert "🇧🇷" in post_msg["text"] and "🇺🇸" in post_msg["text"]
    assert "Post em português" in post_msg["text"]
    assert "Post in English" in post_msg["text"]
    assert post_msg["reply_markup"] is not None

    # Photo enviada com caption truncado do PT
    assert len(b.telegram.sent_photos) == 1
    photo = b.telegram.sent_photos[0]
    assert photo["photo"].startswith("https://storage.googleapis.com/")
    assert "Post em português" in photo["caption"]

    post = await _get_awaiting_post(b.posts)
    assert post.user_prompt == "teste de assunto"
    assert post.body_pt and post.body_en
    assert post.image_url is not None
    assert post.image_gcs_path is not None


@pytest.mark.asyncio
async def test_aprovar_publica_e_transiciona_para_published() -> None:
    """Após Fase F: handle_approval dispara publicação em background → PUBLISHED.

    Fluxo: AWAITING_APPROVAL → APPROVED (síncrono, fecha janela de idempotência)
    → spawn _run_publish → PUBLISHED.
    """
    b = _make_service()
    await b.service.handle_command(CHAT_ID, "x", use_github=False)
    await b.service.wait_pending()
    post = await _get_awaiting_post(b.posts)

    await b.service.handle_approval(CHAT_ID, post.id, "cb1")
    await b.service.wait_pending()

    published = await b.posts.list_by_status(PostStatus.PUBLISHED)
    assert len(published) == 1
    assert published[0].linkedin_post_urn == "urn:li:share:7000000000000000000"
    # 2 edits: PUBLISHING_FOOTER (no clique) + footer com link (após publicar).
    assert len(b.telegram.edited_messages) == 2
    assert "publicando" in b.telegram.edited_messages[0]["text"].lower()
    assert "publicado" in b.telegram.edited_messages[1]["text"].lower()
    assert "https://www.linkedin.com/feed/update/" in b.telegram.edited_messages[1]["text"]
    assert any(c["id"] == "cb1" for c in b.telegram.answered_callbacks)
    assert len(b.linkedin.publish_calls) == 1


@pytest.mark.asyncio
async def test_reprovar_cria_chat_state_e_edita_mensagem() -> None:
    b = _make_service()
    await b.service.handle_command(CHAT_ID, "x", use_github=False)
    await b.service.wait_pending()
    post = await _get_awaiting_post(b.posts)

    await b.service.handle_rejection(CHAT_ID, post.id, "cb1")

    revising = await b.posts.list_by_status(PostStatus.REVISING)
    assert len(revising) == 1
    state = await b.chats.get(CHAT_ID)
    assert state is not None
    assert state.awaiting_revision_for_post_id == post.id
    assert len(b.telegram.edited_messages) == 1
    assert "motivo" in b.telegram.edited_messages[0]["text"].lower()


@pytest.mark.asyncio
async def test_motivo_dispara_regeneracao_sem_repesquisar() -> None:
    b = _make_service()
    await b.service.handle_command(CHAT_ID, "x", use_github=True)
    await b.service.wait_pending()
    post = await _get_awaiting_post(b.posts)
    await b.service.handle_rejection(CHAT_ID, post.id, "cb")
    research_count_antes = len(b.anthropic.research_calls)
    github_count_antes = len(b.github.search_calls)
    body_calls_antes = len(b.post_gen.body_calls)
    photos_antes = len(b.telegram.sent_photos)

    await b.service.handle_free_text(CHAT_ID, "muito formal")
    await b.service.wait_pending()

    # Revisão NÃO refaz pesquisa nem GitHub (reaproveita).
    assert len(b.anthropic.research_calls) == research_count_antes
    assert len(b.github.search_calls) == github_count_antes
    # Mas DISPARA novo body + image (decisão MVP: regenera tudo).
    assert len(b.post_gen.body_calls) == body_calls_antes + 1
    assert len(b.telegram.sent_photos) == photos_antes + 1
    # Header de revisão na mensagem do post.
    ultimo_post_msg = b.telegram.sent_messages[-1]
    assert "Revisão #1" in ultimo_post_msg["text"]
    assert "muito formal" in ultimo_post_msg["text"]

    novo = await _get_awaiting_post(b.posts)
    assert novo.id == post.id
    assert novo.revision_count == 1
    assert "muito formal" in novo.revision_feedback


@pytest.mark.asyncio
async def test_texto_livre_sem_chat_state_e_ignorado() -> None:
    b = _make_service()
    await b.service.handle_free_text(CHAT_ID, "qualquer coisa")
    assert b.telegram.sent_messages == []
    drafts = await b.posts.list_by_status(PostStatus.DRAFT)
    assert len(drafts) == 0


@pytest.mark.asyncio
async def test_novo_comando_com_pendente_em_revising_pergunta_descartar() -> None:
    b = _make_service()
    await b.service.handle_command(CHAT_ID, "primeiro", False)
    await b.service.wait_pending()
    p1 = await _get_awaiting_post(b.posts)
    await b.service.handle_rejection(CHAT_ID, p1.id, "cb1")

    msgs_antes = len(b.telegram.sent_messages)
    await b.service.handle_command(CHAT_ID, "segundo", True)
    await b.service.wait_pending()

    assert len(b.telegram.sent_messages) == msgs_antes + 1
    pergunta = b.telegram.sent_messages[-1]
    assert "pendente" in pergunta["text"].lower()
    assert pergunta["reply_markup"] is not None
    assert len(await b.posts.list_by_status(PostStatus.AWAITING_APPROVAL)) == 0
    state = await b.chats.get(CHAT_ID)
    assert state is not None
    assert state.pending_new_command is not None
    assert state.pending_new_command.user_prompt == "segundo"
    assert state.pending_new_command.use_github is True


@pytest.mark.asyncio
async def test_descartar_sim_rejeita_antigo_e_processa_novo() -> None:
    b = _make_service()
    await b.service.handle_command(CHAT_ID, "primeiro", False)
    await b.service.wait_pending()
    p1 = await _get_awaiting_post(b.posts)
    await b.service.handle_rejection(CHAT_ID, p1.id, "cb1")
    await b.service.handle_command(CHAT_ID, "segundo", False)
    await b.service.wait_pending()

    await b.service.handle_discard_decision(
        chat_id=CHAT_ID, accept=True, callback_query_id="cb2", original_message_id=1
    )
    await b.service.wait_pending()

    rejected = await b.posts.list_by_status(PostStatus.REJECTED)
    assert len(rejected) == 1 and rejected[0].id == p1.id
    assert rejected[0].rejection_cause == RejectionCause.DISCARDED_BY_NEW_COMMAND
    # rejection_detail carrega o prompt do novo comando que disparou o descarte.
    assert rejected[0].rejection_detail == "segundo"
    # revision_feedback do post antigo continua vazio (não houve motivo humano).
    assert rejected[0].revision_feedback == []
    awaiting = await b.posts.list_by_status(PostStatus.AWAITING_APPROVAL)
    assert len(awaiting) == 1 and awaiting[0].user_prompt == "segundo"
    assert await b.chats.get(CHAT_ID) is None


@pytest.mark.asyncio
async def test_descartar_nao_mantem_pendente_e_limpa_pending_new() -> None:
    b = _make_service()
    await b.service.handle_command(CHAT_ID, "primeiro", False)
    await b.service.wait_pending()
    p1 = await _get_awaiting_post(b.posts)
    await b.service.handle_rejection(CHAT_ID, p1.id, "cb1")
    await b.service.handle_command(CHAT_ID, "segundo", False)
    await b.service.wait_pending()

    await b.service.handle_discard_decision(
        chat_id=CHAT_ID, accept=False, callback_query_id="cb2", original_message_id=1
    )

    revising = await b.posts.list_by_status(PostStatus.REVISING)
    assert len(revising) == 1 and revising[0].id == p1.id
    assert len(await b.posts.list_by_status(PostStatus.AWAITING_APPROVAL)) == 0
    state = await b.chats.get(CHAT_ID)
    assert state is not None
    assert state.awaiting_revision_for_post_id == p1.id
    assert state.pending_new_command is None
